# Generated by Django 3.0 on 2019-12-28 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Process',
        ),
    ]
